apiVersion: "v1"
kind: "BuildConfig"
metadata:
  name: "simple-webapp-docker"
spec:
  runPolicy: "Serial"
  triggers:
    -
      type: "GitHub"
      github:
        secret: "b5e471d57f79f52e"
    - type: "Generic"
      generic:
        secret: "4be5b473f9985dcf"
    -
      type: "ImageChange"
  source:
    git:
      uri: "https://github.com/mmumshad/simple-webapp-docker.git"
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: "DockerImage"
        name: "ubuntu:16.04"
  output:
    to:
    kind: "ImageStreamTag"
    name: "simple-webapp:latest"
