apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: simple-webapp-docker-v2
spec:
  output: {}
    to:
      kind: ImageStreamTag
      name: 'simple-webapp-docker:latest'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: 'https://github.com/alexfbasa/simple-webapp-docker.git'
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: DockerImage
        name: 'ubuntu:16.04'
    type: Docker
  triggers:
    - github:
        secret: b5e471d57f79f52e
      type: GitHub
    - generic:
        secret: 4be5b473f9985dcf
      type: Generic
status:
  lastVersion: 5
