kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "simple-test-pipeline"
spec:
  source:
    git:
      uri: "https://github.com/alexfbasa/jenkins-openshift-pipeline.git"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile-test.groovy
